### ISSUE TITLE
Crash while trying to navigate $HOME

### ISSUE THREAD

**Issue by TypicalAM** [mistakenelf/fm#115]
Upstream `fm` crashes when running the app in `$HOME`. Steps to reproduce:
- `go install` on `main`
- `cd ~`
- `fm` shows the directory as empty, pressing `right` causes the program to panic, relevant part of trace below
- Running with `--enable-logging` creates an empty file

Additional info:
- `go version go1.22.9 linux/amd64`
- `tput cols && tput lines # 113 32`
- `echo $TERM $LSCOLORS # tmux-256color Gxfxcxdxbxegedabagacad`

```
Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/lib/golang/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /home/adam/.go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:478 +0x91
panic({0x9459c0?, 0xc000154b28?})
        /usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/mistakenelf/fm/filetree.Model.Update({{0x0, 0x0, 0x0}, 0x0, 0x0, 0x1b, 0x1c, 0x38, 0x0, 0x1, ...}, ...)
        /home/adam/.go/pkg/mod/github.com/mistakenelf/fm@v1.1.0/filetree/update.go:176 +0x68f2
github.com/mistakenelf/fm/internal/tui.model.Update({{{0x0, 0x0, 0x0}, 0x0, 0x0, 0x1b, 0x1c, 0x38, 0x0, 0x1, ...}, ...}, ...)
        /home/adam/.go/pkg/mod/github.com/mistakenelf/fm@v1.1.0/internal/tui/update.go:177 +0x999
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0002a6c30, {0xcc3958?, 0xc0000cd508?}, 0xc0001173e0)
        /home/adam/.go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:411 +0x5e2
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0002a6c30)
        /home/adam/.go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:543 +0x86b
github.com/mistakenelf/fm/cmd.init.func1(0x100cd20, {0x108c5c0?, 0x7?, 0x96f176?})
        /home/adam/.go/pkg/mod/github.com/mistakenelf/fm@v1.1.0/cmd/root.go:88 +0x8a5
github.com/spf13/cobra.(*Command).execute(0x100cd20, {0xc00010e060, 0x0, 0x0})
        /home/adam/.go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x100cd20)
        /home/adam/.go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/adam/.go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/mistakenelf/fm/cmd.Execute()
        /home/adam/.go/pkg/mod/github.com/mistakenelf/fm@v1.1.0/cmd/root.go:107 +0x211
main.main()
        /home/adam/.go/pkg/mod/github.com/mistakenelf/fm@v1.1.0/main.go:6 +0xf
```

**Comment by lazysegtree** [comment]
Able to reproduce 

```
➜  ~ [10:31:50] fm
Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go@1.22/1.22.12/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/homebrew/Cellar/go@1.22/1.22.12/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/Users/kuknitin/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.3/tea.go:475 +0x88
panic({0x104b9c5c0?, 0x1400046a000?})
	/opt/homebrew/Cellar/go@1.22/1.22.12/libexec/src/runtime/panic.go:770 +0x124
github.com/mistakenelf/fm/filetree.Model.Update({{0x0, 0x0, 0x0}, 0x0, 0x0, 0x1c, 0x1d, 0x3f, 0x0, 0x1, ...}, ...)
	/Users/kuknitin/Workspace/kuknitin/fm/filetree/update.go:176 +0x36e4
github.com/mistakenelf/fm/internal/tui.model.Update({{{0x0, 0x0, 0x0}, 0x0, 0x0, 0x1c, 0x1d, 0x3f, 0x0, 0x1, ...}, ...}, ...)
	/Users/kuknitin/Workspace/kuknitin/fm/internal/tui/update.go:176 +0x2544
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x1400041c870, {0x104bcaff0?, 0x140004b6008?}, 0x140000315c0)
	/Users/kuknitin/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.3/tea.go:408 +0x4f4
github.com/charmbracelet/bubbletea.(*Program).Run(0x1400041c870)
	/Users/kuknitin/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.3/tea.go:543 +0x7cc
github.com/mistakenelf/fm/cmd.init.func1(0x104eff860, {0x104f85640?, 0x7?, 0x1047a2638?})
	/Users/kuknitin/Workspace/kuknitin/fm/cmd/root.go:87 +0x7fc
github.com/spf13/cobra.(*Command).execute(0x104eff860, {0x14000020090, 0x0, 0x0})
	/Users/kuknitin/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x104eff860)
	/Users/kuknitin/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/kuknitin/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/mistakenelf/fm/cmd.Execute()
	/Users/kuknitin/Workspace/kuknitin/fm/cmd/root.go:106 +0x20c
main.main()
	/Users/kuknitin/Workspace/kuknitin/fm/main.go:6 +0x1c
➜  ~ [10:31:53]
```

**Comment by lazysegtree** [comment]
@TypicalAM , FYI I have fixed the code issue, which caused this in my system in PR #117 .

**Comment by mistakenelf** [comment]
Fixed in #117
